module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🌸', '🪴', '💫', '🍂', '🌟','🫀', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: '',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: '',
    NEWSLETTER_JID: '',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'ᴀᴋɪɴᴅᴜ-ᴍᴅ',
    OWNER_NAME: 'ᴍʀ ᴀᴋɪɴᴅᴜ',
    OWNER_NUMBER: '94764703165',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> ᴘᴏᴡᴇʀᴇᴅ ʙʏ ᴀᴋɪɴᴅᴜ',
    CHANNEL_LINK: '',
};
